version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  error_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: ERROR
      formatter: standard
      filename: errors.log
      maxBytes: 1048576 # 1MB
      backupCount: 3
      encoding: utf8

root:
  level: DEBUG
  handlers: [console, error_file_handler]
